# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  # using major version aliases

  # aliased to 5.2.17
  #- 5.2
  # aliased to 5.3.29
  - 5.3
  # aliased to a recent 5.4.x version
  - 5.4
  # aliased to a recent 5.5.x version
  - 5.5
  # aliased to a recent 5.6.x version
  - 5.6
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: 5.6
    - php: hhvm

# optionally specify a list of environments, for example to test different RDBMS
env:
  - DB=mysql
#  - DB=pgsql

sudo: required

# execute any number of scripts before the test run, custom env's are available as variables
before_script:
    - if [[ $HHVM == false ]]; sudo apt-get install apache2 libapache2-mod-fastcgi; fi
    # enable php-fpm
    - if [[ $HHVM == false ]]; sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf; fi
    - if [[ $HHVM == false ]]; sudo a2enmod rewrite actions fastcgi alias; fi
    - if [[ $HHVM == false ]]; echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
    - if [[ $HHVM == false ]]; ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm; fi
    # configure apache virtual hosts
    - if [[ $HHVM == false ]]; sudo cp -f etc/travis-ci/travis-ci-apache /etc/apache2/sites-available/default; fi
    - if [[ $HHVM == false ]]; sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default; fi
    - if [[ $HHVM == false ]]; sudo service apache2 restart; fi
#  - if [[ "$DB" == "pgsql" ]]; then psql -c "DROP DATABASE IF EXISTS hello_world_test;" -U postgres; fi
#  - if [[ "$DB" == "pgsql" ]]; then psql -c "create database hello_world_test;" -U postgres; fi
    - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS miana;" -uroot; fi
    - if [[ "$DB" == "mysql" ]]; then mysql -u root miana < files/pharinix.sql; fi

# omitting "script:" will default to phpunit
# use the $DB env variable to determine the phpunit.xml to use
script: 
    - phpunit --configuration etc/travis-ci/phpunit.xml.dist

# configure notifications (email, IRC, campfire etc)
notifications:
  email: "aaaaa976@gmail.com"
